# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PaddleBall < Formula
  desc "A minimalist physics-based terminal paddleball game with score history"
  homepage "https://paddleball.mvp-subha.me"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/subhadeeproy3902/paddle-ball/releases/download/v1.0.3/paddle-ball_darwin_amd64.tar.gz"
      sha256 "d1fdcad9513c48ecb208f550a16483beb46bbb49bbda4c8b2290785f347a729b"

      define_method(:install) do
        bin.install "paddle-ball"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/subhadeeproy3902/paddle-ball/releases/download/v1.0.3/paddle-ball_darwin_arm64.tar.gz"
      sha256 "3870ea611deae13db02ae2e84d93316f88bf1a8388dfc9fb68341210224d5716"

      define_method(:install) do
        bin.install "paddle-ball"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/subhadeeproy3902/paddle-ball/releases/download/v1.0.3/paddle-ball_linux_amd64.tar.gz"
      sha256 "f09b14332a0f92e4aaa48ad1a4a16c5f2061bbd08d88469f5862454af87f1e1c"
      define_method(:install) do
        bin.install "paddle-ball"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/subhadeeproy3902/paddle-ball/releases/download/v1.0.3/paddle-ball_linux_arm64.tar.gz"
      sha256 "c6cf99a64988c5e7e83a40ffe25f949a19e2ff426292ca78f7bcf45e333f0f44"
      define_method(:install) do
        bin.install "paddle-ball"
      end
    end
  end

  test do
    system "#{bin}/paddle-ball version"
  end
end
