# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PongBall < Formula
  desc "A minimalist physics-based terminal Pong game with score history"
  homepage "https://pongball.mvp-subha.me"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.0.0/pong-ball_darwin_amd64.tar.gz"
      sha256 "6e296abc07aa752b9d00a27d0a74d7eacbcbedec081156602ebfdcc5efea148d"

      define_method(:install) do
        bin.install "pong-ball"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.0.0/pong-ball_darwin_arm64.tar.gz"
      sha256 "5a5a25244a8df0df77b621ac9f63b1c7e1d19bc374ca2c8ecdbc723625dd6097"

      define_method(:install) do
        bin.install "pong-ball"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.0.0/pong-ball_linux_amd64.tar.gz"
      sha256 "2840b5c0b94a74f15d3d9da80c6e57c473b6f14c443fac46effc79b83f7e2de3"
      define_method(:install) do
        bin.install "pong-ball"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.0.0/pong-ball_linux_arm64.tar.gz"
      sha256 "6ddcfd3f5f77099baaeab909f38d47e7a5fb1a4f0ab6b16910cf9a6eb4e90c40"
      define_method(:install) do
        bin.install "pong-ball"
      end
    end
  end

  test do
    system "#{bin}/pong-ball version"
  end
end
