# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PongBall < Formula
  desc "A minimalist physics-based terminal Pong game with score history"
  homepage "https://pongball.mvp-subha.me"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.1.0/pong-ball_darwin_amd64.tar.gz"
      sha256 "caf1b7825000bd23257b13b223870c1f774df67c336be295c9d85a53efcad430"

      define_method(:install) do
        bin.install "pong-ball"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.1.0/pong-ball_darwin_arm64.tar.gz"
      sha256 "198ee6e89587f117889ee42926603b3c7bde7c6f40e59ea5fe29fc41440818eb"

      define_method(:install) do
        bin.install "pong-ball"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.1.0/pong-ball_linux_amd64.tar.gz"
      sha256 "8fd8f2bed18e51e90796adef98e0f4eeaac66a034ce4379727e02e601aee0601"
      define_method(:install) do
        bin.install "pong-ball"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.1.0/pong-ball_linux_arm64.tar.gz"
      sha256 "ad68289cf322768c43fb15522756206819ee531b6d8721cc575a712183add601"
      define_method(:install) do
        bin.install "pong-ball"
      end
    end
  end

  test do
    system "#{bin}/pong-ball version"
  end
end
