# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PongBall < Formula
  desc "A minimalist physics-based terminal Pong game with score history"
  homepage "https://pongball.mvp-subha.me"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.0.1/pong-ball_darwin_amd64.tar.gz"
      sha256 "5421739a82595696288c8fe5688fc0aee10c9050181b4b8200b3f27e6b346ff3"

      define_method(:install) do
        bin.install "pong-ball"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.0.1/pong-ball_darwin_arm64.tar.gz"
      sha256 "cd6500600b529e7b7c2e85703b16167ec2611547228b9fb737e2e0b00b8033c2"

      define_method(:install) do
        bin.install "pong-ball"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.0.1/pong-ball_linux_amd64.tar.gz"
      sha256 "1340b23aae1883b07c517b0a3c9f198980bca47a917611884e3d08dd436e2c94"
      define_method(:install) do
        bin.install "pong-ball"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/subhadeeproy3902/pong-ball/releases/download/v1.0.1/pong-ball_linux_arm64.tar.gz"
      sha256 "2ac2ef4cb0632cca34d47261575f08a5e372ad65ae9f83fdff85e2e56159e645"
      define_method(:install) do
        bin.install "pong-ball"
      end
    end
  end

  test do
    system "#{bin}/pong-ball version"
  end
end
